name: Docker Image CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: "${{ github.actor }}"
        DOCKERHUB_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        ./build.sh
